def mvn_version = 'jenkins-maven'
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               
                withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
                 //sh "mvn clean package"
                    sh 'mvn -B -DskipTests clean package'
                }
                
            }
        }
        stage('Test') {
            steps {
                withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
                 //sh "mvn clean package"
                    sh 'mvn test'
                }
               
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ){
                sh '''
                    chmod +x ./jenkins/scripts/deliver.sh
                    ./jenkins/scripts/deliver.sh
                '''
                }
            }
        }
    }
}
