def mvn_version = 'jenkins-maven'
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               
                withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
                 //sh "mvn clean package"
                    sh 'mvn -B -DskipTests clean package'
                }
                
            }
        }
        
		stage('Deploy') {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:'pcf',
				usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']
			]){
			
				sh 'cf login -a  https://api.run.pivotal.io -u vamsi111087@gmail.com - p @Lakshya123 -s development -o Vamsi11'
			}
            }
        }
    }
}
